language: python

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.5"
    - os: osx
      python: "2.7"
    - os: osx
      python: "3.5"

script:
  - which python
  - python --version
  - python -m unittest discover test
