sudo: required
dist: trusty

language: python

matrix:
  include:
    - os: linux
      python: "2.7"
      sudo: required
      env: CONDA=N
    - os: linux
      python: "3.5"
      sudo: required
      env: CONDA=N
    - os: linux
      python: "2.7"
      sudo: required
      env:
        - CONDA=Y
        - CONDAPY=2.7
    - os: linux
      python: "3.5"
      sudo: required
      env:
        - CONDA=Y
        - CONDAPY=3.5
    - os: osx
      language: generic
      env:
        - OSXENV=2.7
        - CONDA=N
    - os: osx
      language: generic
      env:
        - OSXENV=3.5
        - CONDA=N

before_install:
  - bash resources/before_install.sh
  - if [[ "$CONDA" == "N" ]]; then bash resources/install_dependencies.sh; fi
  - if [[ "$CONDA" == "Y" ]]; then bash resources/conda_setup.sh; fi

script:
  - if [[ "$CONDA" == "Y" ]]; then export PATH="$HOME/miniconda/bin:$PATH"; fi
  - if [[ "$CONDA" == "Y" ]]; then source activate condaenv; fi
  - which python
  - python -m unittest discover test
