sudo: required
dist: trusty

language: python

matrix:
  include:
    - os: linux
      python: "2.7"
      sudo: required
    - os: linux
      python: "3.5"
      sudo: required
    - os: osx
      language: generic
      env: OSXENV=2.7
    - os: osx
      language: generic
      env: OSXENV=3.5

before_install:
  - resources/before_install.sh

script:
  - which python
  - python -m unittest discover test
