image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYVER: 3
      BITS: 32
    - PYTHON: "C:\\Python37"
      PYVER: 3
      BITS: 32
    - PYTHON: "C:\\Python38"
      PYVER: 3
      BITS: 32
    - PYTHON: "C:\\Python39"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYVER: 3
      BITS: 32
    - PYTHON: "C:\\Python310"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYVER: 3
      BITS: 32
    - PYTHON: "C:\\Python36-x64"
      PYVER: 3
      BITS: 64
    - PYTHON: "C:\\Python37-x64"
      PYVER: 3
      BITS: 64
    - PYTHON: "C:\\Python38-x64"
      PYVER: 3
      BITS: 64
    - PYTHON: "C:\\Python39-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYVER: 3
      BITS: 64
    - PYTHON: "C:\\Python310-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYVER: 3
      BITS: 64

init:
  - "ECHO %PYTHON% %vcvars% (%bits%)"
  - ps: $env:PATH = "$env:PYTHON;$env:PATH;"
  - python -c "import sys;print('Python version is {}'.format(sys.version))"

build: false

install:
  - python -m pip install --upgrade pip
  - pip install pytest
  - python setup.py install

test_script:
  - pytest
