name: run-tests
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
jobs:
  run-dependency-test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install gtk dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install libffi-dev libglib2.0-dev
          sudo apt-get install gobject-introspection libgtk-3-dev
          sudo apt-get install python3-gi
      - name: Install general dependencies
        run: |
          python setup.py install
          pip install pytest
      - name: Run tests
        run: pytest
