name: run-tests
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
jobs:
  run-conda-test:
    name: Running tests using miniconda
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: deptest-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,pkgw-forge
      - name: Show conda details
        run: |
          conda info
          conda list
          which python
          conda --version
      - name: Install Linux conda dependencies
        if:  matrix.os == 'ubuntu-latest'
        run: echo "I am ubuntu"
      - name: Install MacOS conda dependencies
        if:  matrix.os == 'macos-latest'
        run: echo "I am macos"
