name: run-tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  test-darwin-conda:
    name: Running tests using miniconda
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      # upgrade to latest checkout version
      - uses: actions/checkout@v2
      # upgrade to latest version
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: deptest-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,pkgw-forge
      - name: Linux conda
        if:  matrix.os == 'ubuntu-latest'
        run: echo "Running Ubuntu"
      - name: MacOS conda
        if:  matrix.os == 'macos-latest'
        run: echo "Running MacOS"
      - name: Show conda details
        run: |
          conda info
          conda list
          which python
          conda --version
      - name: Installation
        # upgrade to not use deprecated setup.py install any longer
        run: python setup.py install
      - name: Install test dependencies
        run: pip install pytest
      - name: Run tests
        run: pytest

  test-darwin-plain:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]
    steps:
      # upgrade to latest version
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        # upgrade to latest version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python setup.py install
          pip install -r requirements-test.txt
      - name: Run tests
        run: pytest

  test-win-plain:
    continue-on-error: true
    runs-on: [windows-latest]
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      # upgrade to latest version
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        # upgrade to latest version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python setup.py install
          pip install -r requirements-test.txt
      - name: Run tests
        run: pytest

  run-coverall:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python setup.py install
          pip install pytest coveralls
      - name: Create coverage
        run: |
          coverage run --source=bren -m pytest test/
      - name: Submit to coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github

  run-codecov:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python setup.py install
          pip install pytest pytest-cov
      - name: Create coverage
        run: |
          pytest --cov=./ --cov-report=xml
      - uses: codecov/codecov-action@v1
        with:
          name: Submit Codecov coverage
          files: ./coverage.xml
          verbose: true # optional (default = false)
